### ISSUE TITLE
Navigate to method declaration from template files

### ISSUE THREAD

**Issue by Rambomst** [php-integrator/atom-navigation#32]
Is it possible to alt+click class/method names within template files to go to where they are defined? I have been unable to get this navigation package working for our template files. It also seems to only work in in our custom php files sometimes (file extension is .gpx and we use the file-types package to set the source to `text.html.php`).

**Comment by Gert-dev** [comment]
By itself, the analyzer can't deduce the type of something like this:

```html
<html>
    <body>
        <?php
            echo $this-> // Won't work.
...
```

This is because there is no way to know who's instantiating the template without some kind of framework-specific behavior. However, you _can_ help the type analyzer by explicitly stating what the type is:

```html
<html>
    <body>
        <?php
            /** @var \SomeNamespace\MyController $this */
            echo $this-> // Shows members of MyController. Navigation to them should now also work.
...
```

This of course only works if the type of that part of the file is PHP. In any case, if the file-types package is setting the syntax highlighting language, you should at least be able to get completion on the `$` sign to list superglobals. If that doesn't work either, then something else is wrong.

**Comment by Rambomst** [comment]
I tried adding that comment into the template files and it still didn't work.

Also it should know what this is without the need for a comment right?
```
{$testing = TestClass::count()}
```

How should I go about debugging this?

**Comment by Gert-dev** [comment]
It should indeed. Did you try using the FQCN (i.e. with leading slash) when adding the type hint? There may be a bug in the released version that doesn't always properly resolve non-FQCN paths. The development version (which will be released soonish as 2.0) has fixed a large amount of these sorts of issues and consistency problems, but that doesn't help you much right now, of course.

It could also be that the type of the PHP code is not properly being recognized as PHP code by this package and is by consequence not properly being indexed. To debug this, you can open up the developer tools in Atom (`Ctrl + Shift + I` on Windows/Linux), search for the file `php-integrator-base/Main.coffee` and put a breakpoint in `onEditorDidStopChanging` to see if it fails on the check for `text.html.php`. If this passes and works correctly, it is likely to be an issue on the PHP side instead.

**Comment by Rambomst** [comment]
It is detecting our template files as `text.html.smarty` which would be correct. Should `text.html.php` not be hard coded but rather allow the user to choose which files they want this to work on?

**Comment by Gert-dev** [comment]
I did not realize it was Smarty code, that indeed currently doesn't work as I can't parse Smarty template code as being PHP code since Smarty's syntax isn't entirely compatible with PHP. Even if you were to add it to the list (you can always give it a try), it is likely to fail on the PHP side later on as the PHP parser can't parse the Smarty-specific syntax. However, plain HTML interleaved with PHP (i.e. the old way to do templates with PHP itself) should work.

I assume it would be possible to build some kind of plugin package specific to Smarty (I know Peekmo built one for Twig and php-autocomplete-plus, but it integrates tightly with Symfony and won't work with any other framework using Twig). When parsing a Smarty file (with a Smarty parser, a regular expression parser, ...), you would still need to figure out somehow what type a variable is, which depends on what the controller is assigning to it (which could be _any_ controller). You could also solve that by manually annotating the file (much like PHP's type override annotations).

**Comment by Gert-dev** [comment]
I'll close this since support for template languages is a bit out of the scope of this package.
