### ISSUE TITLE
Alt+Clicking class name opens in same window, not new new tab

### ISSUE THREAD

**Issue by zacksmash** [php-integrator/atom-navigation#38]
This only happens if you've just opened Atom and only have one file open. If you have multiple files open, it works as expected.

**Comment by Gert-dev** [comment]
Hello! I'm not sure I completely understand what you mean, if I understood correctly:

1. You start Atom. It has one window and there is only one PHP file open in it.
2. You navigate to a class name (e.g. from a use statement) that is defined in another file.
3. The navigation opens the file of the class in the active tab instead of creating a new tab.

Is this what you mean?

**Comment by zacksmash** [comment]
Correct. It seems to only be on newly indexed sites as well. I'm having trouble re-creating the issue in that same project, now that I've closed and re-opened Atom. But it definitely behaved that way initially.

**Comment by Gert-dev** [comment]
When it happened, did the tab title remain the same, but its contents seemed to have been replaced with the contents of the file you were navigating to?

**Comment by zacksmash** [comment]
So, I just created a new project and tested it again. It changes the tab title and the contents get swapped out, in the same tab. It doesn't open a new tab.

**Comment by Gert-dev** [comment]
I think I understand what you mean. In the past, I have had a similar issue occur once in a while. I think it's an Atom issue, as this package only requests Atom to open the appropriate filename at the appropriate line. From then on, it's Atom who decides if opening a new tab is necessary or the tab is already open, needs to be activated, and scrolled to the appropriate location.

I had thought about reporting it, but I haven't had the issue for a while now. However, if you can consistently reproduce the steps, it may be worthwile to report it to [Atom's repository](https://github.com/atom/atom/issues). I'm guessing it has something to do with Atom confusing the active tab for a pending tab and closing it automatically.

I'll close this as I don't think this bug is located in this package, but thanks for taking the time to report it.
